language: android
jdk:
    - oraclejdk8
sudo: false

android:
    components:
        - platform-tools
        - tools
        - build-tools-27.0.3
        - android-22
        - android-27
        - sys-img-armeabi-v7a-android-22
        - extra-android-m2repository
        - extra-google-m2repository

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

# Emulator Management: Create, Start and Wait

before_script:
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a -c 500M
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
script:
  - bash ./gradlew build check connectedCheck
