#!/bin/bash

# Copies the compressed Blockly JavaScript files from a local copy of
# Blockly for Web.
#
# Usage:
#   updatejs [SourceDir]
# where SourceDir is the directory path to a local copy of web Blockly.
# By default, this is assumed to be ../web.


WEB_BLOCKLY_PATH="../web"
CORE_ASSETS_PATH="blocklylib-core/src/main/assets"
DEMO_ASSETS_PATH="blocklydemo/src/main/assets"

# space delimited source/destination filename pairs
FILES=(\
  "blockly_compressed.js ${CORE_ASSETS_PATH}/blockly_compressed.js"\
  "blocks_compressed.js ${CORE_ASSETS_PATH}/blocks_compressed.js"\
  "javascript_compressed.js ${CORE_ASSETS_PATH}/javascript_compressed.js"\
  "msg/js/en.js ${CORE_ASSETS_PATH}/msg/js/en.js"\
  "lua_compressed.js ${DEMO_ASSETS_PATH}/lua/lua_compressed.js"
)

ERROR_RUN_AT_ROOT=1
ERROR_DIR_NOT_FOUND=2
ERROR_MISSING_FILES=3

if [ ! -d "./blocklylib-core" ]; then
  >&2 echo "Please run from root of blockly-android git repo"
  exit $ERROR_RUN_AT_ROOT
fi

if [[ ! -z $1 ]]; then
  # Strip the trailing slash, and make sure it is a directory
  if [ -d ${1%/} ]; then
    WEB_BLOCKLY_PATH=${1%/}
  else
    >&2 echo "Unknown directory: ${1}"
    exit $ERROR_DIR_NOT_FOUND
  fi
fi

found_files=true
for i in "${FILES[@]}"; do
  files=(${WEB_BLOCKLY_PATH}/$i)
  src=${files[0]}
  dest=${files[1]}
  if [[ ! -r $src ]]; then
    found_files=false
    echo "ERROR: File missing: $src"
  fi 
done

if [ ! $found_files = true ]; then
  exit $ERROR_MISSING_FILES
fi

for i in "${FILES[@]}"; do
  files=(${WEB_BLOCKLY_PATH}/$i)
  src=${files[0]}
  dest=${files[1]}
  echo "cp $src $dest"
  cp $src $dest
done
exit 0
